import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export async function exportPdf(
  title: string,
  hourlyScore: number,
  annualScore: number,
  consumptionName: string,
  generationMix: Record<string, number>
): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = margin

  // Header
  pdf.setFontSize(18)
  pdf.setTextColor(0, 152, 139) // teal-700
  pdf.text('Scenario Analysis Tool', margin, y)
  y += 8

  if (title.trim()) {
    pdf.setFontSize(14)
    pdf.setTextColor(42, 41, 41) // neutral-1000
    pdf.text(title.trim(), margin, y)
    y += 8
  }

  // Divider
  pdf.setDrawColor(227, 224, 221) // neutral-300
  pdf.line(margin, y, pageWidth - margin, y)
  y += 8

  // Scores
  pdf.setFontSize(11)
  pdf.setTextColor(42, 41, 41)
  pdf.text('Hourly Matching Score:', margin, y)
  pdf.setTextColor(0, 152, 139)
  pdf.setFontSize(16)
  pdf.text(`${Math.round(hourlyScore)}%`, margin + 55, y)

  pdf.setFontSize(11)
  pdf.setTextColor(42, 41, 41)
  pdf.text('Annual Matching Score:', margin + 90, y)
  pdf.setTextColor(137, 127, 120) // neutral-600
  pdf.setFontSize(16)
  pdf.text(`${Math.round(annualScore)}%`, margin + 145, y)
  y += 10

  // Configuration
  pdf.setFontSize(10)
  pdf.setTextColor(42, 41, 41)
  pdf.text(`Consumption profile: ${consumptionName}`, margin, y)
  y += 6

  pdf.text('Generation mix:', margin, y)
  y += 5
  pdf.setFontSize(9)
  pdf.setTextColor(86, 81, 78) // neutral-800
  const activeTechs = Object.entries(generationMix).filter(([, pct]) => pct > 0)
  if (activeTechs.length === 0) {
    pdf.text('  No generation technologies selected', margin, y)
    y += 5
  } else {
    for (const [tech, pct] of activeTechs) {
      pdf.text(`  ${tech}: ${pct}%`, margin, y)
      y += 4.5
    }
  }
  y += 4

  // Capture charts
  const resultsEl = document.querySelector('.results-section') as HTMLElement | null
  if (resultsEl) {
    const canvas = await html2canvas(resultsEl, {
      scale: 2,
      backgroundColor: '#FBFAF9',
      logging: false,
      useCORS: true,
    })

    const imgData = canvas.toDataURL('image/png')
    const imgWidth = contentWidth
    const imgHeight = (canvas.height / canvas.width) * imgWidth

    // Check if we need a new page
    const pageHeight = pdf.internal.pageSize.getHeight()
    if (y + imgHeight > pageHeight - margin) {
      pdf.addPage()
      y = margin
    }

    pdf.addImage(imgData, 'PNG', margin, y, imgWidth, imgHeight)
    y += imgHeight + 6
  }

  // Footer
  const pageHeight = pdf.internal.pageSize.getHeight()
  pdf.setFontSize(8)
  pdf.setTextColor(137, 127, 120)
  pdf.text(
    'Generated by Granular Energy Scenario Analysis Tool — www.granular-energy.com',
    margin,
    pageHeight - 8
  )

  // Save
  const filename = title.trim()
    ? `scenario-analysis-${title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`
    : 'scenario-analysis.pdf'
  pdf.save(filename)
}
